apiVersion: v1
kind: PersistentVolume
metadata:
  name: kungfu-efs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kungfu-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs_id}
