output "vpc_id" {
    value = module.vpc.vpc_id
}
output "vpc_name" {
    value = var.vpc_name
}

output "default_securitygroup" {
    value = module.vpc.default_security_group_id
}

output "private_key_path" {
    value = var.private_key_path
}

output "cluster_id" {
    value = module.eks.cluster_id
}

output "cluster_name" {
    value = var.cluster_name
}

output "KubeNodeSecurityGroup" {
    value = aws_security_group.KubeNodeSecurityGroup.id
}



output "cluster_endpoint" {
    description = "Endpoint for EKS control plane."
    value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
    description = "Security group ids attached to the cluster control plane."
    value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
    description = "kubectl config as generated by the module."
    value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
    description = "A kubernetes configuration to authenticate to this EKS cluster."
    value       = module.eks.config_map_aws_auth
}
